### PR TITLE
WIP Pull in rbac client

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by Magisus** [comment]
Locally this is failing to find the artifact, even though other projects (e.g. pe-rbac-service) with the same dep (rbac-client 0.9.2) work fine. What am I missing?

**Comment by justinstoller** [comment]
The client is closed source

**Comment by Magisus** [comment]
Oh shoot, you're right, that makes sense. Hmm...

**Comment by justinstoller** [comment]
I'd actually expect this to work locally on the vpn but not in travis. It looks like its failing locally because you specified a release and we only have our internal snapshot repo configured (and we are still pointing at our nexus alias which should change).

**Pull request closed without merging**
