### PR TITLE
(MAINT) Update CHANGELOG for 0.5.0 release

### PR DESCRIPTION
**Pull request by nwolfe**

### CODE REVIEW

**Comment by nwolfe** [comment]
@camlow325 @dankreek

**Comment by camlow325** [comment]
:+1: on the notes.  Did you want to bump the project.clj version in this PR as well?  I think we have to do that b/c we're doing a Y version bump, IIRC.

**Comment by nwolfe** [comment]
> Did you want to bump the project.clj version in this PR as well? I think we have to do that b/c we're doing a Y version bump, IIRC.

Going to try the lein-release patch level parameter to adjust the version number.

**Comment by nwolfe** [comment]
> Going to try the lein-release patch level parameter to adjust the version number.

Release plugin can't help us here.

Ready for merge

**Comment by camlow325** [comment]
:+1:

**Pull request merged**
